// constants/notificationTypes.js
module.exports = Object.freeze({
    USER_SIGNUP: "USER_SIGNUP",
    USER_DELETED: "USER_DELETED",
    THEATER_ADDED: "THEATER_ADDED",
    THEATER_UPDATED: "THEATER_UPDATED",
    THEATER_DELETED: "THEATER_DELETED",
    SCREEN_ADDED: "SCREEN_ADDED",
    SCREEN_UPDATED: "SCREEN_UPDATED",
    SCREEN_DELETED: "SCREEN_DELETED",
    MOVIE_ADDED: "MOVIE_ADDED",
    MOVIE_UPDATED: "MOVIE_UPDATED",
    MOVIE_DELETED: "MOVIE_DELETED",
    SHOW_ADDED: "SHOW_ADDED",
    SHOW_UPDATED: "SHOW_UPDATED",
    SHOW_DELETED: "SHOW_DELETED",
    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
    BOOKING_CANCELED: "BOOKING_CANCELED",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAILED: "PAYMENT_FAILED"
  });
  